<?xml version="1.0"?>
<robot name="limo_mobile" xmlns:xacro="http://ros.org/wiki/xacro">

<!-- Variables -->
<xacro:property name="M_PI" value="3.14159"/>

<!-- Vehicle Geometries -->
<xacro:property name="base_x_size" value="0.13" />
<xacro:property name="base_y_size" value="0.12" />
<xacro:property name="base_z_size" value="0.1" />

<xacro:property name="wheelbase" value="0.2"/>
<xacro:property name="track" value="0.13"/>
<xacro:property name="wheel_vertical_offset" value="-0.10" />
<xacro:property name="base_mass" value="2.1557"/>

<!-- Wheel Geometries -->
<xacro:property name="wheel_length" value="0.001" />
<xacro:property name="wheel_radius" value="0.045" />

<!-- Base Footprint LINK -->
<link name="base_footprint"/>

<!-- Base Footprint JOINT -->
<joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0.0 0.0 0.15" rpy="0 0 0"/>
</joint>

<!-- Base link -->
<link name="base_link">
    <visual>
        <origin xyz="0 0 -0.15" rpy="0 0 1.57" />
        <geometry>
            <mesh filename="package://lab1_mobile_ackermann/meshes/limo_optimal.dae" scale="1 1 1"/>
        </geometry>
    </visual>
    <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <box size="${base_x_size} ${base_y_size} ${base_z_size}"/>
        </geometry>
    </collision>
    <inertial>
        <origin xyz="0.0 0.0 0.0" />
        <mass value="${base_mass}" />
        <inertia ixx="0.0043832566666666675" ixy="0" ixz="0" 
                    iyy="0.004832360833333334" iyz="0" 
                    izz="0.005622784166666667" />
    </inertial>
</link>

<!-- Front Left Wheel -->

<link name="front_left">
    <inertial>
        <mass value="0.25" />
        <inertia ixx="0.00525" ixy="0" ixz="0" iyy="0.00035" iyz="0" izz="0.00525" />
        <origin xyz="0 0 0" />
    </inertial>
    <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <cylinder length="0.0001" radius="0.0001" />
        </geometry>
    </visual>
</link>

<joint name="front_left_steering" type="revolute">
    <parent link="base_link"/>
    <child link="front_left"/>
    <xacro:insert_block name="joint_pose"/>
    <axis xyz="0 0 1" />
    <limit lower="-0.523598767" upper="0.523598767" effort="1000" velocity="1.0" />
    <dynamics damping="0.0" friction="2.0"/>
</joint>

<link name="front_left_wheel_link">
    <inertial>
        <mass value="0.25" />
        <inertia ixx="0.00525" ixy="0" ixz="0" iyy="0.00035" iyz="0" izz="0.00525" />
        <origin xyz="0 0 0" />
    </inertial>
    <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <mesh filename="package://lab1_mobile_ackermann/meshes/limo_optimal_wheels.dae" />
        </geometry>
    </visual>
    <collision>
        <origin xyz="0 ${wheel_length/2} 0" rpy="1.57 0 0" />
        <geometry>
            <cylinder length="${wheel_length}" radius="${wheel_radius}" />

        </geometry>
    </collision>
</link>