controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    velocity_controllers:
      type: velocity_controllers/JointGroupVelocityController

    position_controllers:
      type: position_controllers/JointGroupPositionController

velocity_controllers:
  ros__parameters:
    use_sim_time: true
    joints: 
      - front_left_wheel_joint
      - front_right_wheel_joint
      - rear_left_wheel_joint
      - rear_right_wheel_joint
    command_interface: 
      - velocity
    state_interface: 
      - velocity
      - effort

position_controllers:
  ros__parameters:
    use_sim_time: true
    joints: 
      - front_left_steering_joint
      - front_right_steering_joint
    command_interface: 
      - position
    state_interface: 
      - position
      - velocity
      - effort